name: C Hello World
description: A GitHub Action written in C that prints "Hello, World!"

runs:
  using: "composite"
  steps:
    - name: Set up C environment
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential

    - name: Build and run C action
      shell: bash
      run: |
        gcc main.c -o hello
        ./hello